[mypy]
python_version = 3.9
strict = True
pretty = True
show_error_codes = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
files = src, tests

[mypy-click.*]
ignore_missing_imports = True

[mypy-pytest]
follow_imports = skip

[mypy-pytest.*]
follow_imports = skip

[mypy-_pytest.*]
follow_imports = skip
