"""Fixture-backed demo environment helpers."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from unittest.mock import patch

from palisade.core.artifact import export_scan_bundle
from palisade.core.config import write_default_config
from palisade.core.db import initialize_db_path
from palisade.core.device import DeviceFingerprint, ProbeConfig
from palisade.core.kev import import_kev_json_file, sync_source_adapter
from palisade.core.kev_sources import FileKevSourceAdapter
from palisade.core.report import ReportFilters, render_report
from palisade.edge_audit.scanner import EdgeAuditScanner, ScanOptions

DEMO_ROOT = Path(__file__).resolve().parents[3] / "demo"
DEMO_DATA_DIR = DEMO_ROOT / "data"


@dataclass(frozen=True)
class DemoBuildResult:
    """Paths generated by the demo builder."""

    output_dir: Path
    db_path: Path
    config_path: Path
    latest_scan_id: str
    baseline_scan_id: str
    latest_report_path: Path
    diff_report_path: Path
    bundle_path: Path


def build_demo_environment(output_dir: Path) -> DemoBuildResult:
    """Create a repeatable PALISADE demo environment under the given directory."""
    output_dir.mkdir(parents=True, exist_ok=True)
    db_path = output_dir / "palisade-demo.db"
    reports_dir = output_dir / "reports"
    bundles_dir = output_dir / "bundles"
    reports_dir.mkdir(parents=True, exist_ok=True)
    bundles_dir.mkdir(parents=True, exist_ok=True)
    config_path = output_dir / "palisade.demo.json"
    write_default_config(config_path)

    connection = initialize_db_path(db_path)
    import_kev_json_file(connection, DEMO_DATA_DIR / "kev_demo.json")
    sync_source_adapter(
        connection,
        FileKevSourceAdapter(DEMO_DATA_DIR / "supplemental_citrix_demo.json"),
    )

    scanner = EdgeAuditScanner(connection)
    baseline_scan_id = run_demo_scan(
        scanner,
        [
            DeviceFingerprint(
                ip="198.51.100.10",
                port=443,
                vendor="Fortinet",
                product="FortiOS",
                version="7.2.4",
                method="http_header",
                raw_data="demo fortinet",
                confidence="high",
            ),
            DeviceFingerprint(
                ip="198.51.100.11",
                port=443,
                vendor="SonicWall",
                product="SonicOS",
                version="7.0.1-5035",
                method="http_header",
                raw_data="demo sonicwall",
                confidence="high",
            ),
        ],
    )
    latest_scan_id = run_demo_scan(
        scanner,
        [
            DeviceFingerprint(
                ip="198.51.100.11",
                port=443,
                vendor="SonicWall",
                product="SonicOS",
                version="7.0.1-5035",
                method="http_header",
                raw_data="demo sonicwall",
                confidence="high",
            ),
            DeviceFingerprint(
                ip="198.51.100.12",
                port=443,
                vendor="Citrix",
                product="NetScaler ADC",
                version="14.1-6.50",
                method="http_header",
                raw_data="demo citrix",
                confidence="high",
            ),
        ],
    )

    latest_scan = scanner.get_scan(latest_scan_id)
    assert latest_scan is not None
    devices, findings = scanner.get_scan_rows(latest_scan_id)
    diff = scanner.diff_scans(baseline_scan_id, latest_scan_id)

    latest_report_path = reports_dir / "latest-report.txt"
    latest_report_path.write_text(
        render_report("text", latest_scan, devices, findings),
        encoding="utf-8",
    )
    diff_report_path = reports_dir / "diff-report.txt"
    diff_report_path.write_text(
        render_report(
            "text",
            latest_scan,
            devices,
            findings,
            filters=ReportFilters(),
            diff=diff,
        ),
        encoding="utf-8",
    )

    bundle_path = bundles_dir / f"{latest_scan_id}.zip"
    export_scan_bundle(connection, latest_scan_id, bundle_path)
    write_demo_summary(
        output_dir=output_dir,
        latest_scan_id=latest_scan_id,
        baseline_scan_id=baseline_scan_id,
        latest_report_path=latest_report_path,
        diff_report_path=diff_report_path,
        bundle_path=bundle_path,
    )
    return DemoBuildResult(
        output_dir=output_dir,
        db_path=db_path,
        config_path=config_path,
        latest_scan_id=latest_scan_id,
        baseline_scan_id=baseline_scan_id,
        latest_report_path=latest_report_path,
        diff_report_path=diff_report_path,
        bundle_path=bundle_path,
    )


def run_demo_scan(scanner: EdgeAuditScanner, fingerprints: list[DeviceFingerprint]) -> str:
    """Run a scan using fixed demo fingerprints."""
    def fake_fingerprint_host(
        ip: str,
        ports: list[int] | tuple[int, ...],
        *,
        config: ProbeConfig | None = None,
    ) -> list[DeviceFingerprint]:
        del ports, config
        return [fingerprint for fingerprint in fingerprints if fingerprint.ip == ip]

    with patch("palisade.edge_audit.scanner.fingerprint_host", fake_fingerprint_host):
        result = scanner.scan(
            sorted({fingerprint.ip for fingerprint in fingerprints}),
            ScanOptions(concurrency=1, kev_scope="expanded"),
        )
    return result.scan_id


def write_demo_summary(
    *,
    output_dir: Path,
    latest_scan_id: str,
    baseline_scan_id: str,
    latest_report_path: Path,
    diff_report_path: Path,
    bundle_path: Path,
) -> None:
    """Write a concise demo summary file."""
    summary_path = output_dir / "SUMMARY.md"
    summary_path.write_text(
        "\n".join(
            [
                "# PALISADE Demo Output",
                "",
                f"- Baseline scan: `{baseline_scan_id}`",
                f"- Latest scan: `{latest_scan_id}`",
                f"- Latest report: `{latest_report_path.name}`",
                f"- Diff report: `{diff_report_path.name}`",
                f"- Bundle: `{bundle_path.name}`",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
